routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Mail;
// use App\Http\Controllers\AdminController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DashboardPostController;
// use App\Http\Controllers\PostController;
use App\Http\Controllers\ForgotPasswordController;
// use App\Http\Controllers\AdsqooController;
// use App\Http\Controllers\EmailBlastController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//home route
// Route::get('/admin', 'AdminController@index');
Route::get('/home', function () {
    // return view('dashboard.posts.index');
    return view('dashboard.index');
})->middleware('auth');

//test pages
Route::get('/test', function () {
    return view('profile');
})->middleware('auth');

//user route
// Route::get('/signup', 'RegisterController@index');
// Route::post('/signupstore', 'RegisterController@signupstore');
Route::get('/signup', [RegisterController::class, 'index'])->middleware('guest');
Route::post('/signup', [RegisterController::class, 'store']);

Route::get('/signin', [LoginController::class, 'index'])->name('login')->middleware('guest');
Route::post('/logout', [LoginController::class, 'logout']);
Route::post('/signin', [LoginController::class, 'authenticate']);

//verify email
Route::get('send-email', function () {
    Mail::to('suryafauzan199@gmail.com')
        ->send(new \App\Mail\MailtrapLogin(''));
    dd("Email Confirmation.");
});

// Auth::routes(['verify' => true]);

//profile route
Route::get('/profile', [UserController::class, 'profile']);

// // crud route
// Route::get('/pegawai', [PostController::class, 'index']);
// Route::get('/pegawai/tambah', [PostController::class, 'tambah']);
// Route::post('/pegawai/store', [PostController::class, 'store']);
// Route::get('/pegawai/edit/{id}', [PostController::class, 'edit']);
// Route::post('/pegawai/update',[PostController::class, 'update']);
// Route::get('/pegawai/hapus/{id}',[PostController::class, 'hapus']);

//resources route
Route::resource('/home/posts', DashboardPostController::class)->middleware('auth');

//forgot pwd 
// Route::get('/forgot', [ForgotPasswordController::class, 'forgot']);
// Route::post('/forgot', [ForgotPasswordController::class, 'store']);

Route::get('forget', [ForgotPasswordController::class, 'showForgetPasswordForm'])->name('forget.password');
Route::post('forget', [ForgotPasswordController::class, 'submitForgetPasswordForm'])->name('forget.password.post');
Route::get('reset-password/{token}', [ForgotPasswordController::class, 'showResetPasswordForm'])->name('reset.password.get');
Route::post('reset-password', [ForgotPasswordController::class, 'submitResetPasswordForm'])->name('reset.password.post');

//ADSQOO
// Route::get('/adsqoo', [AdsqooController::class, 'index'])->name('dashboard-adsqoo');
// Route::get('/adsqoo-dtp', [AdsqooController::class, 'show'])->name('dashboard-adsqoo-dtp');

//EmailBlast
// Route::get('/email-home', [EmailBlastController::class, 'index'])->name('dashboard-emailblast');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use HasFactory;
    use SoftDeletes;
    protected $guarded = ['id'];
    protected $dates = ['deleted_at'];
    protected $fillable = ['nik', 'name', 'jeniskelamin', 'nohp', 'umur', 'jabatan','alamat','image'];
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;


class PostController extends Controller
{

    // public function __construct()
    // {
    //     $this->middleware('auth');
    // }

    public function index()
    {
    	// mengambil data dari table pegawai
    	$pegawai = DB::table('posts')->get();

    	// mengirim data pegawai ke view index
    	return view('index',['pegawai' => $pegawai]);

    }

    public function tambah()
    {
        //memanggil view tambah
        return view ('tambah');
    }

    //method for insert data
    public function store(Request $request)
    {
        //insert data ke db pegawai
        DB::table('posts')->insert([
            'nik' => $request->nik,
            'name' => $request->nama,
            'jabatan' => $request->jabatan,
            'umur' => $request->umur,
            'alamat' => $request->alamat
        ]);
        //redirect ke /pegawai
        return redirect('/pegawai');
    }

    //methon for edit data pegawai
    public function edit($id)
    {
        //mengambil data pegawai berdasarkan id
        $pegawai = DB::table ('posts')->where('id', $id)->get();
        //passing data pegawai yang didapat ke view edit.blade.php
        return view('edit',['pegawai' => $pegawai]);   
    }

    //update data pegawai
    // public function update(Request $request)
    // {
    //     //update data pegawai
    //     DB::table('posts')->where('id')->update ([
    //         'nik' => $request->nik,
    //         'name' => $request->nama,
    //         'jabatan' => $request->jabatan,
    //         'umur' => $request->umur,
    //         'alamat' => $request->alamat
    //     ]);
    //     //alihkan halaman ke halaman pegawai
    //     return redirect ('/pegawai');
    // }
    public function update(Request $request, $id)
    {
        $model = DB::find($id);
        $model->nik = $request->nik;
        $model->name = $request->name;
        $model->jabatan = $request->jabatan;
        $model->umur = $request->umur;
        $model->alamat = $request->alamat;
        $model->save();
        return redirect()->back()->with('success','Data updated successfully');
    }

    //method untuk menghapus data pegawai
    public function hapus($id)
    {
        //menghapus data pegawai berdasarkan id yang dipilih
        DB::table('posts')->where('id',$id)->delete();

        //alihkan halaman ke halaman pegawai
        return redirect ('/pegawai');
    }
}

resources/views/dashboard/posts/index.blade.php
@extends('dashboard.layouts.main' ,['title' => 'Home'])

@section('container')
           <!-- Page Inner --> 
            <div class="page-inner">
                <nav aria-label="breadcrumb" class="mt1">
                    <ol class="breadcrumb">
                      <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                      <li class="breadcrumb-item active"><a href="#">Single Sends</a></li>
                    </ol>
                </nav>
                <div class="page-title mt2 mb1">
                    <h3 class="breadcrumb-header">Single Sends</h3>
                </div>
                {{-- @if(session()->has('success'))
                <div class="alert alert-success" role="alert">
                  {{ session('success') }}
                </div>
                @endif --}}
                <p class="mb2">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>

                <div class="flex-center">
                    <div>
                        <a href="{{ route('posts.create') }}" class="btn btn-default-2 btn-addon"><i class="fa fa-plus"></i>Single Sends</a>
                    </div>
                </div>
                <div id="main-wrapper">
                    <div class="row mt2">
                        <div class="col-lg-12 col-md-12 cols">
                            <div class="panel panel-white">
                                <div class="panel-body">
                                    <div class="table-responsive have-dropdown custom-table">
                                        <table id="myTable" class="display table" style="width: 100%; cellspacing: 0;">
                                            <thead>
                                                <tr>
                                                    <th>ID</th>
                                                    <th>NIK</th>
                                                    <th>Name Karyawan</th>
                                                    <th>Jabatan</th>
                                                    <th width="150">Action</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                              @foreach ($posts as $post)
                                                <tr>
                                                    <td>{{ $loop->iteration }}</td>
                                                    <td>{{ $post->nik }}</td>
                                                    <td>{{ $post->name }}</td>
                                                    <td>{{ $post->jabatan }}</td>
                                                    {{-- <td>{{ $post->umur }}</td> --}}
                                                    {{-- <td>{{ $post->alamat }}</td> --}}
                                                    {{-- <td>{{ $post->image }}</td> --}}
                                                    <td class="flex-center pos-relative">
                                                        {{-- <a href="" class="btn btn-default btn-addon" data-toggle="modal" data-target="#myModal4"><i class="fa fa-gear"></i>Manage</a>
                                                        <button type="button" class="btn btn-default more dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></button>
                                                        <div class="dropdown-menu custom">
                                                            <a class="dropdown-item" href="/home/posts/{{ $post->id }}/edit">Edit</a>
                                                            <a class="dropdown-item" href="#" >
                                                              <form action="/home/posts/{{ $post->id }}" method="post">
                                                                @method('delete')
                                                                @csrf
                                                                <h5 onclick="return confirm('Delete data?')">Remove</h5>
                                                              </form>
                                                            </a>
                                                        </div> --}}
                                                        <div class="input-group-prepend">
                                                          <button type="button" class="btn btn-default btn-addon dropdown-toggle" data-toggle="dropdown">
                                                            <i class="fa fa-gear"></i>
                                                            Manage
                                                          </button>
                                                          <ul class="dropdown-menu">
                                                            {{-- <li class="dropdown-item"><a data-toggle="modal" data-target="#myModal4">Details</a></li> --}}
                                                            <li class="dropdown-item"><a class="dropdown-item" href="{{ route('posts.show', $post->id) }}">Details</a></li>
                                                            <li class="dropdown-item"><a class="dropdown-item" href="{{ route('posts.edit', $post->id) }}">Modify</a></li>
                                                          </ul>
                                                        </div>
                                                        <div class="input-group-prepend">
                                                            <form action="{{ route('posts.destroy', $post->id) }}" method="POST" class="d-inline delete">
                                                                @method('delete')
                                                                @csrf
                                                                <button class="btn btn-default more" oneclick="question"><i class="fa fa-trash"></i></button>
                                                            </form>
                                                        </div>
                                                        <!-- /btn-group -->
                                                    </td> 
                                                </tr>
                                                @endforeach
                                            </tbody>
                                        </table>  
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- Row -->
                </div><!-- Main Wrapper -->
            </div><!-- /Page Inner -->
@endsection

resources/views/dashboard/posts/show.blade.php
@extends('dashboard.layouts.main',['title' => 'Show'])

@section('container')

            <!-- general form elements disabled -->
            <div class="card card-warning">
              <div class="card-header">
                <h3 class="card-title">Read Only Details Pegawai</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <form>
                  {{-- <div class="row">
                    <div class="col-sm-6">
                      <div class="form-group">
                        <label>NIK Pegawai</label>
                        <input type="text" class="form-control" disabled placeholder="{{ $posts->nik }}">
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-sm-6">
                      <div class="form-group">
                        <label>Nama Pegawai</label>
                        <input type="text" class="form-control" disabled placeholder="{{ $posts->name }}">
                      </div>
                    </div>
                  </div>
                  <div class="row">
                  <div class="col-sm-6">
                    <div class="form-group">
                      <label>Jenis Kelamin</label>
                      <input type="text" class="form-control" disabled placeholder="{{ $posts->jeniskelamin }}">
                    </div>
                  </div>
                  </div>
                  <div class="row">
                  <div class="col-sm-6">
                    <div class="form-group">
                      <label>No Handphone</label>
                      <input type="text" class="form-control" disabled placeholder="{{ $posts->nohp }}">
                    </div>
                  </div>
                  </div>
                  <div class="row">
                    <div class="col-sm-6">
                      <div class="form-group">
                        <label>Umur Pegawai</label>
                        <input type="text" class="form-control" disabled placeholder="{{ $posts->umur }}">
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-sm-6">
                      <div class="form-group">
                        <label>Jabatan Pegawai</label>
                        <input type="text" class="form-control" disabled placeholder="{{ $posts->jabatan }}">
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-sm-6">
                      <div class="form-group">
                        <label>Alamat Pegawai</label>
                        <input type="text" class="form-control"  disabled placeholder="{{ $posts->alamat }}">
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-sm-6">
                      <div class="form-group">
                        <label>Foto Kayrawan</label>
                        <div>
                        <img width="125px" height="75px" src="{{ asset('storage/' . $posts->image) }}" alt="default" style="object-fit: cover;">
                        <p class="text-muted">{{ $posts->created_at->format('Y-M-d') }} &middot; {{ $posts->created_at->diffForHumans() }}</p>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="d-flex">
                <a href="{{ route('posts.index') }}" class="btn btn-success"><span data-feather="arrow-left"></span>Back To Data Pegawai</a>
                <a href="{{ route('posts.edit', $posts->id) }}" class="btn btn-warning"><span data-feather="edit"></span>Edit Data Pegawai</a>
                </div> --}}


                <div class="col-lg-6 col-md-6 col-xs-12 cols">
                  <div class="panel panel-white">
                    <div class="panel-body">
                        <div class="row flex-center">
                          <div class="col-lg-12 col-md-12 col-xs-12">
                            <div class="title-default">Detail Pegawai</div>
                            <br>
                            <div class="list-info no-border">
                              <div class="row info-detail">
                                  <div class="col-lg-5 col-md-5 left">NIK Pegawai</div>
                                  <div class="col-lg-6 col-md-6">: {{ $posts->nik }}</div>
                              </div>
                              <div class="row info-detail">
                                  <div class="col-lg-5 col-md-5 left">Name Pegawai</div>
                                  <div class="col-lg-6 col-md-6">: {{ $posts->name }}</div>
                              </div>
                              <div class="row info-detail">
                                  <div class="col-lg-5 col-md-5 left">Jenis Kelamin</div>
                                  <div class="col-lg-6 col-md-6">: {{ $posts->jeniskelamin }}</div>
                              </div>
                              <div class="row info-detail">
                                  <div class="col-lg-5 col-md-5 left">No Handphone</div>
                                  <div class="col-lg-6 col-md-6">: {{ $posts->nohp }}</div>
                              </div>
                              <div class="row info-detail">
                                  <div class="col-lg-5 col-md-5 left">Umur</div>
                                  <div class="col-lg-6 col-md-6">: {{ $posts->umur }}</div>
                              </div>
                              <div class="row info-detail">
                                  <div class="col-lg-5 col-md-5 left">Jabatan</div>
                                  <div class="col-lg-6 col-md-6">: {{ $posts->jabatan }}</div>
                              </div>
                              <div class="row info-detail">
                                  <div class="col-lg-5 col-md-5 left">Alamat</div>
                                  <div class="col-lg-6 col-md-6">: {{ $posts->alamat }}</div>
                              </div>
                              {{-- <div class="row"> --}}
                                  {{-- <div class="col-lg-5 col-md-5 left">Foto Pegawai</div>
                                  <div class="col-lg-6 col-md-6">
                                    <img width="125px" height="75px" src="{{ asset('storage/' . $posts->image) }}" alt="default" style="object-fit: cover;">
                                    <p class="text-muted">{{ $posts->created_at->format('Y-M-d') }} &middot; {{ $posts->created_at->diffForHumans() }}</p>
                                  </div> --}}
                                  <div class="panel panel-white">
                                    <div class="panel-body">
                                      <div class="title-default mb2">Foto Karyawan</div>
                                      <iframe width="250px" height="200px" src="{{ asset('storage/' . $posts->image) }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                                      <p class="text-muted">{{ $posts->created_at->format('Y-M-d') }} &middot; {{ $posts->created_at->diffForHumans() }}</p>
                                    </div>
                                  </div>
                              {{-- </div> --}}
                              <div class="row">
                                <div class="col-sm-12">
                                  <ul class="pager wizard no-margin">
                                    <li class="next" data-target="#step2">
                                      <a href="{{ route('posts.index') }}" class="btn btn-default-2 primary"><span data-feather="arrow-left"></span>Home</a>
                                    </li>
                                  </ul>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                    </div>
                  </div>
                </div>
                </form>
                {{-- <div class=""> --}}
                {{-- <form action="{{ route('posts.destroy', $posts->id) }}" method="POST" class="d-inline">
                  @method('delete')
                  @csrf
                  <button class="btn btn-danger" onclick="return confirm('Delete data?')"><span data-feather="x-circle"></span>Delete Data Pegawai</button>
                </form> --}}
                {{-- </div> --}}
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
            <!-- general form elements disabled -->

@endsection